language: ruby
rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - ruby-head

before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq -y install mplayer libmagick9-dev

#test against ruby-head as well so we know what's coming down the pipe
matrix:
  allow_failures:
    - rvm: ruby-head
